Korrigert litt informasjon og lagt til informasjon om ack, nack og nackWithRequeue
ks-no/ks-no.github.io pull request #88
Opened 2024-07-11 08:24 UTC by jarleborsheim

2024-07-11 11:27 UTC, mortenaa requested changes

2024-07-11 11:32 UTC, jarleborsheim commented on content/Tjenester/fiksprotokoll/fiksio.md
> +Dette betyr at man fort "bruker opp" antall forsøk på å lese meldingen og den havner i DLQ (dead-letter-queue) og deretter blir til en feilmelding tilbake til avsender.
Ja, det er jo forsåvidt det Oslo må gjøre. Men det har vært implementasjoner hvor de har hatt 3 samtidige konsumenter hvor 2 av dem kjører nackWithRequeue fordi det er bare den tredje som skal ha denne typen melding, som er en elendig ide. Derfor liker jeg ikke at vi sier at nackWithRequeue skal brukes. Men kanskje jeg skal forsøke å skrive tydelig noe om når det kan brukes allikevel.

2024-07-11 11:33 UTC, jarleborsheim commented on content/Tjenester/fiksprotokoll/fiksio.md
> +Hvis man får denne Fiks IO serverfeil meldingen tilbake så betyr det at noe har gått galt og Fiks IO har håndtert det.
Ja, jeg ser den. Endrer teksten 👍

2024-08-05 07:59 UTC, mortenaa approved these changes

2024-08-05 08:04 UTC, merged